"""
Django settings for crm_api project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r$9qx=yn^54*k*mukar2c^)txhl4*_fnv+o8exvnd7)cq47z(e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'account',
    'order',
    'opportunity',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xgyypt',
        'USER': 'root',
        'PASSWORD': '1CzoOCywfJ*h',
        'HOST': '192.168.185.33',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'yqms2_32': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yqms2',
        'USER': 'fbeta',
        'PASSWORD': '9yacto9659d',
        'HOST': '192.168.30.2',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },

    'contract_33': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'contract',
        'USER': 'root',
        'PASSWORD': '1CzoOCywfJ*h',
        'HOST': '192.168.185.33',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'yqms2_199': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yqms2',
        'USER': 'fuser',
        'PASSWORD': '97yu1r221pxeyt3',
        'HOST': '192.168.16.199',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'log_120': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'log',
        'USER': 'loguser',
        'PASSWORD': 'f693b823',
        'HOST': 'mysql-yqms-log.istarshine.net.cn',
        # 'HOST': '192.168.19.120',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'yqht_199': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yqht',
        'USER': 'fuser',
        'PASSWORD': '97yu1r221pxeyt3',
        'HOST': '192.168.16.199',
        'PORT':3306,
        'OPTIONS':{'isolation_level':None}
    },
    'zhwp_new': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'zhwp_new',
        'USER': 'fuser',
        'PASSWORD': '7ga7iv13a5',
        'HOST': '192.168.19.6',
        'PORT': 3306,
        'OPTIONS': {'isolation_level': None}
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
